---
#service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-sagar
  name: demo-sagar
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-sagar
  type: ClusterIP
---
#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-sagar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-sagar
  template:
    metadata:
      labels:
        app: demo-sagar
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
        instrumentation.opentelemetry.io/container-names: "spring"
    spec:
      containers:
      - name: spring
        image: sagar27/petclinic-demo
        ports:
        - containerPort: 8080
